server:
  port: 8100
debug: false
spring:
  application:
    name: appointment-service
  datasource:
    url: jdbc:mysql://localhost:3306/doctorapp
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  main:
    allow-circular-references: true
  sql:
    init:
      platform: mysql
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
logging:
  level:
    sql: trace
    web: info
    root: info
